DOCSP-27804 add mapReduce Limitation
mongodb/docs-cluster-to-cluster-sync pull request #117
Opened 2023-03-20 21:51 UTC by kennethdyer

## Description

Adds `mapReduce` to `$out` limitations.

## Staging
* [Filtering with mapReduce & $out](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-27804-add-mapReduce/reference/collection-level-filtering/#filtering-with-mapreduce-and--out)
* [Limitations](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-27804-add-mapReduce/reference/collection-level-filtering/#limitations) (Changes made to last bullet point).

## Jira

[DOCSP-27804](https://jira.mongodb.org/browse/DOCSP-27804)

## Build

[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6418d26cb070a41637f8721d)

[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=641b12bab070a41637727069)

[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6421e42666f244bf57e361ef)

2023-03-22 14:27 UTC, kennethdyer commented on source/reference/collection-level-filtering.txt
> +These operations can be used with filtering only when you filter
Fixed

2023-03-22 14:28 UTC, kennethdyer commented on source/reference/collection-level-filtering.txt
> +database command can create new collections when run.
Refactored.  The "can" was there because output is optional for `mapReduce`.

2023-03-23 13:55 UTC, ajhuh-mdb requested changes
Thanks for making these adjustments @kennethdyer! This version of the copy reads much clearer and streamlined. Just had a couple more notes before this should be ready to go.

2023-03-24 15:14 UTC, kennethdyer commented on source/includes/limitations-filtering.rst
> +  requires that you configure the filter to use the entire database.
Fixed

2023-03-24 15:22 UTC, ajhuh-mdb commented on source/reference/collection-level-filtering.txt
> +the specified collection.
Ah noted! Sorry about that, I meant to refer to active voice in linking that section of the style guide. 😅

2023-03-24 15:28 UTC, ajhuh-mdb approved these changes
Thanks for making these edits, @kennethdyer! This LGTM with one nit suggestion to help with the parsability of one sentence.

2023-03-27 18:44 UTC, kennethdyer commented on source/reference/collection-level-filtering.txt
> +the :dbcommand:`mapReduce` command set to create
Fixed

2023-03-27 19:20 UTC, rohshar approved these changes
LGTM

2023-03-27 19:24 UTC, merged