DOCSP-28563 Adds telemetry option and setting
mongodb/docs-cluster-to-cluster-sync pull request #122
Opened 2023-04-07 21:11 UTC by kennethdyer

## Description

Adds the `--disableTelemetry` option and setting for `mongosync`.

## Staging

* [`--disableTelemtry` option](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28563-telemetry-toggle/reference/mongosync/#std-option-mongosync.--disableTelemetry)

* [`disableTelemetry` setting](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28563-telemetry-toggle/reference/configuration/#mongodb-setting-disableTelemetry)

## Jira

[DOCSP-28563](https://jira.mongodb.org/browse/DOCSP-28563)

## Build
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64307673b49106a498392f36)

2023-04-11 13:53 UTC, mdb-ashley approved these changes
This LGTM, Kenneth! Nice work.

2023-04-11 13:53 UTC, mdb-ashley commented on source/includes/opts/disableTelemetry.rst
> +Disables the collection and sharing of ``mongosync`` telemetry data with MongoDB.
[praise] Nice work making this an include!

2023-04-11 15:52 UTC, kennethdyer commented
Marking this one as blocked, per Ajay Vijaykumar.  They don't want to ship it until the backing feature is ready (to happen sometime after 1.3.0).

2023-05-30 15:53 UTC, ajayvijayakumar123 requested changes
Left a couple of suggestions. Thanks!

2023-05-30 15:53 UTC, ajayvijayakumar123 commented on source/includes/opts/disableTelemetry.rst
> +Disables the collection and sharing of ``mongosync`` telemetry data with MongoDB.
Here's a link to Segment: https://segment.com/
```suggestion
Disables the sharing of ``mongosync`` telemetry data with Segment. 
```

2023-05-30 15:53 UTC, ajayvijayakumar123 commented on source/includes/opts/disableTelemetry.rst
> +
Could we also include on the docs that we will **not** be tracking IP addresses, hostnames, usernames, passwords, credentials, data stored in users' MongoDB deployments, or personable identifiable information when sending telemetry to Segment?

2023-06-09 19:20 UTC, davemungo commented
This was incorporated into
 
DOCSP-29499 [REP] Add Telemetry to mongosync
https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/128

2023-06-09 19:20 UTC, closed without merging