DOCSP-22785 disclaimer banner
mongodb/docs-cluster-to-cluster-sync pull request #14
Opened 2022-05-31 17:02 UTC by davemungo

I'm sending this one out for external review first since it requires specific wording from the product management and possibly legal teams. 

[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22785-disclaimer-banner/)

[JIRA](https://jira.mongodb.org/browse/DOCSP-22785)
[C2C] Create "In preview" banner

2022-05-31 19:53 UTC, alan-zheng-mdb requested changes

2022-05-31 19:53 UTC, alan-zheng-mdb commented on source/includes/preview-warning-top.rst
> +
Similar to how other "Preview" features are mentioned in DOCs, please see https://docs-atlas-staging.mongodb.com/cloud-docs/docsworker-xlarge/DOCSP-22663/data-federation/query/query-with-sql/. 

Prefer the "blue" banner vs the "red". 

Below is the shortened text that I would like to use
`Cluster-to-Cluster Sync is available as a Preview feature. This feature and the corresponding documentation may change at any time during the Preview phase. Cluster-to-Cluster Sync should not be used in production systems.`

2022-05-31 21:00 UTC, davemungo reviewed
Thanks @alan-zheng-mdb  - this is ready for another pass

2022-06-01 15:00 UTC, alan-zheng-mdb approved these changes

2022-06-01 15:39 UTC, merged