DOCSP-33784-capped-remediation
mongodb/docs-cluster-to-cluster-sync pull request #175
Opened 2023-11-04 00:00 UTC by jason-price-mongodb

2023-11-06 16:42 UTC, rohshar requested changes
It seems that for every other change needed, it has its own section below the table as well. I would follow that same format.

2023-11-08 17:36 UTC, jason-price-mongodb commented on source/reference/disaster-recovery.txt
> +       allowable size. Use the ``collMod`` command to set your required
Will do. Was following the standard already set for all the other text in the section.

2023-11-08 17:48 UTC, jason-price-mongodb commented on source/reference/disaster-recovery.txt
> +       maximum size.
Done.

2023-11-08 18:38 UTC, jason-price-mongodb commented
@rohshar please re-review. I've also added a new section per your request. Cheers.

2023-11-08 21:10 UTC, rohshar requested changes

2023-11-08 21:10 UTC, rohshar commented on source/reference/disaster-recovery.txt
> +   * - :ref:`Capped Collections <c2c-dr-capped-collections>`
I don't really want them to say the same thing. This should be a summary compared to below which has all of the information.

What about putting something like: "Synchronization sets capped collections to the maximum allowable size. Use the collMod command to resize capped collections"

2023-11-08 22:25 UTC, jason-price-mongodb commented
@rohshar please re-review. Thanks.

2023-11-08 22:55 UTC, rohshar approved these changes
I'm LGTMing this, but please update the link before merging

2023-11-08 22:55 UTC, rohshar commented on source/reference/disaster-recovery.txt
> +       size. To set your required maximum size, use the ``collMod``
I think this should be a link to collMod

2023-11-08 23:04 UTC, merged