DOCSP-33399 role limitation
mongodb/docs-cluster-to-cluster-sync pull request #248
Opened 2024-01-26 22:29 UTC by kennethdyer

## Description

Adds sync limitation: mongosync does not sync users and roles.

## Staging

* [General Limitations](https://preview-mongodbkennethdyer.gatsbyjs.io/cluster-sync/DOCSP-33399-role-limitation/reference/limitations/#general-limitations) (last entry)

## JIRA

[DOCSP-33399](https://jira.mongodb.org/browse/DOCSP-33399)

## Build

* [2023-01-26](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b4300994771f76570acc82)

2024-01-26 22:44 UTC, mmaville-mdb approved these changes
LGTM!

2024-01-30 15:47 UTC, FGasper commented on source/reference/limitations.txt
> +- ``mongosync`` doesn't sync users and roles.
```suggestion
- ``mongosync`` doesn't sync users or roles.
```

2024-01-30 15:48 UTC, FGasper requested changes
One quick change to the verbiage seems apropos.

Thanks!

2024-01-31 17:25 UTC, FGasper approved these changes
LGTM. Thanks!

2024-02-01 19:49 UTC, merged