DOCS-15748 Fix Mongosync Atlas doc examples
mongodb/docs-cluster-to-cluster-sync pull request #276
Opened 2024-02-29 18:07 UTC by kanchana-mongodb

- [JIRA](https://jira.mongodb.org/browse/DOCS-15748)
- Stage: 
  - [Atlas to Atlas](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCS-15748/connecting/atlas-to-atlas/)
  - [Self-Managed to Atlas](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCS-15748/connecting/onprem-to-atlas/)
- [Build](url)

2024-03-01 17:52 UTC, kennethdyer reviewed
Thanks for this work @kanchana-mongodb, I left a few comments for your consideration.

2024-03-01 17:52 UTC, kennethdyer commented on source/includes/example-connect-onprem-to-atlas.rst
> +- clusterOne01.fancyCorp.com:20020
We should use inline code to format these URL's.

2024-03-01 17:52 UTC, kennethdyer commented on source/includes/example-connect-onprem-to-atlas.rst
> +The source cluster, ``cluster0``, is hosted on the following servers
Given that this occurs at the start of a new section, replace `cluster0` and `cluster1` with
```
:setting:`cluster0`
:setting:`cluster1`
```
to provide the appropriate links.

2024-03-01 17:52 UTC, kennethdyer commented on source/includes/example-connect-onprem-to-atlas.rst
> +.. code-block:: shell
For this code block, set the format to text since it's a raw example and doesn't need syntax highlighting.

2024-03-01 17:52 UTC, kennethdyer commented on source/includes/example-connect-onprem-to-atlas.rst
> +.. code-block:: shell
This block doesn't provide a shell example of the `--cluster0` option.  Instead it's showing an example of the YAML configuration file, so it should use the `yaml` syntax highlighter.

2024-03-01 17:52 UTC, kennethdyer commented on source/includes/fact-connection-strings-onprem.rst
> +:binary:`mongod` instances.
[Suggestion]: I'd recommend 
```
:program:`mongod`
:program:`mongos`
``` 
I'm not sure that it matters under the hood, but it seems to be what we're transitioning to.

2024-03-01 17:52 UTC, kennethdyer commented on source/connecting/atlas-to-atlas.txt
> +- ``mongosync`` does not support Atlas shared clusters or serverless
[Suggestion]: I like to bold the "not" in phrases like this to make sure the reader sees it.

2024-03-05 17:32 UTC, AleGonez requested changes
Requested changes seems to be OK. However, I’m seeing some repeated information in [Connect a Self-Managed Cluster to Atlas](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCS-15748/connecting/onprem-to-atlas/) stage link. Following information is twice:

![image](https://github.com/mongodb/docs-cluster-to-cluster-sync/assets/38086209/e638e4f7-ae15-4705-b42b-78160a01e2fd)

Can you please remove the duplicated info?
I'm not seeing this was part of the changes for this PR though but it would be good to correct it before publishing. Let me know if this will be handled in a separate PR and I can approve this one.

2024-03-05 20:19 UTC, AleGonez approved these changes

2024-03-05 21:12 UTC, kennethdyer commented on source/includes/example-connect-onprem-to-atlas.rst
> +.. code-block:: shell
I'm still seeing these set to shell.  They should be `text` or `none`.

2024-03-05 21:12 UTC, kennethdyer commented on source/includes/example-connect-onprem-to-atlas.rst
> +.. code-block:: shell
Not seeing the change here, either.

2024-03-06 17:18 UTC, merged