DOCSP-23937 Fix Role Issue on Mongosync Start Page
mongodb/docs-cluster-to-cluster-sync pull request #287
Opened 2024-03-18 21:21 UTC by kanchana-mongodb

- [JIRA](https://jira.mongodb.org/browse/DOCSP-23937):

Document for [setUserWriteBlockMode](https://www.mongodb.com/docs/master/reference/privilege-actions/#mongodb-authaction-setUserWriteBlockMode) and [bypassWriteBlockingMode](https://www.mongodb.com/docs/master/reference/privilege-actions/#mongodb-authaction-bypassWriteBlockingMode) specify that these roles should be applied to the cluster resource, but current example in doc shows these applied on the db/collection. Fixes incorrect documentation.
 
- [Stage](url) 
- [Build](url)

2024-03-18 21:31 UTC, kennethdyer approved these changes
Thanks @kanchana-mongodb, This LGTM!

2024-03-20 16:07 UTC, rohshar reviewed
I think this becomes overly complicated in trying to tell the users how to create custom roles instead of just linking to the reserve part of the user permissions section: https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/permissions/

I'm not sure why this was added initially, and since it isn't totally correct, I'm not sure if anyone has used it.

@tfogo any thoughts?

2024-03-20 16:34 UTC, tfogo commented
@rohshar For a quick start I think it is important to have all the steps laid out in a way that users can easily copy and paste. So I think it is good practice to have a command. Linking to the permissions doc works, but having the command is better.

2024-03-26 15:56 UTC, rohshar commented
My issue is that the commands listed in the quickstart are for creating a custom role, but seem to have been wrong before. I think rather than prompting users to create custom roles, it is probably better for them to use the built in roles, hence linking to the permissions doc.

2024-04-05 17:46 UTC, rohshar requested changes
Synced with Tim. Since this isn't in the quickstart, we shouldn't add documentation that is totally different than what is present in https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/permissions/

Instead, I think we should only mention that they can check the permissions needed in the permissions page and create a custom role with those here.

2024-04-05 18:23 UTC, tfogo commented
Yeah apologies, I saw the file name was "start" and thought it was the quick start.

2024-04-09 13:14 UTC, rohshar approved these changes

2024-04-09 13:27 UTC, merged