DOCSP-38149 Add documentation for mongosync cutover processs
mongodb/docs-cluster-to-cluster-sync pull request #292
Opened 2024-04-03 15:15 UTC by kanchana-mongodb

- [JIRA](url)
- [Stage](url)
- [Build](url)

2024-04-03 18:29 UTC, tdq45gj requested changes
The current sequence of steps still doesn't seem correct to me. The sequence should be:

1. Verify the status of the [mongosync](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-38149/reference/mongosync/#std-program-mongosync) process.
2. Stop any write operations to the synced collections on the source
3. Send a [commit](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-38149/reference/api/commit/#std-label-c2c-api-commit) request to mongosync.
4. Wait for `canWrite` to become true
5. Enable application writes on the destination cluster.
6. Call the [progress](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-38149/reference/api/progress/#std-label-c2c-api-progress) endpoint to determine the status of the mongosync process.

2024-04-03 18:29 UTC, tdq45gj commented on source/reference/cutover-process.txt
> +   .. step:: Call the :ref:`progress <c2c-api-progress>` endpoint.
Suggested change: Wait for `canWrite` to become true.

2024-04-04 13:58 UTC, tdq45gj approved these changes
LGTM, thank you!

2024-04-04 14:29 UTC, jmd-mongo reviewed
Thank you for this addition, @kanchana-mongodb! I've left some suggestions and a question for your consideration.

Thank you!
Joe

2024-04-04 14:29 UTC, jmd-mongo commented on source/reference/cutover-process.txt
> +      Call the :ref:`progress <c2c-api-progress>` endpoint to determine
[linking suggestion]

Consider using backticks around "progress" instead of linking as this is already linked above.

2024-04-04 14:29 UTC, jmd-mongo commented on source/reference/cutover-process.txt
> +   .. step:: Call the :ref:`progress <c2c-api-progress>` endpoint to determine the status of the ``mongosync`` process.
Similar comment as on line 67.

2024-04-04 14:29 UTC, jmd-mongo commented on source/reference/cutover-process.txt
> +      until :ref:`progress <c2c-api-progress>` shows ``canWrite`` is
Simliar comment as on line 67.

2024-04-04 14:29 UTC, jmd-mongo commented on source/reference/cutover-process.txt
> +   .. step:: Enable application writes on the destination cluster.
[question]

Should there be a code example or blurb here showing how to enable writes on the destination cluster?

2024-04-04 18:29 UTC, jmd-mongo approved these changes
Thank you for these changes, @kanchana-mongodb! This issue LGTM mod a minor code formatting nit. 

Thank you!
Joe

2024-04-04 18:29 UTC, jmd-mongo commented on source/reference/cutover-process.txt
> +         db.adminCommand(
[code formatting suggestion]

I recommend using formatting similar to the following. It's a minor change to be less indented.

```
db.adminCommand(
   {
      setUserWriteBlockMode: 1,
      global: false
   }
)
```

2024-04-04 18:29 UTC, jmd-mongo commented on source/reference/cutover-process.txt
> +   .. step:: Enable application writes on the destination cluster.
Thank you!

2024-04-04 18:58 UTC, merged