DOCSP-34591 Add errorDescription and success keys to progress response
mongodb/docs-cluster-to-cluster-sync pull request #295
Opened 2024-04-03 20:38 UTC by kanchana-mongodb

- [JIRA](https://jira.mongodb.org/browse/DOCSP-34591)
- [Stage](reference/api/progress/#error-response)
- [Build](url)

2024-04-04 12:21 UTC, mmcclimon requested changes
One tweak to make, plus two other changes on the page (https://preview-mongodbkanchanamongodb.gatsbyjs.io/cluster-sync/DOCSP-34591/reference/api/progress/#response-1) that aren't in this .rst file:

First, just above the error response table:
> If mongosync encounters an error, the progress endpoint returns the following field:

This should be "fields" (plural).

Second: the `success` boolean field is also returned for non-error responses. I don't know if we want to document this in the table, but I think we should at least update the sample successful response to this (note the top-level "success" key):

```
{
   "success":  true,
   "progress":
      {
         "state":"RUNNING",
         "canCommit":true,
         "canWrite":false,
         "info":"change event application",
         "lagTimeSeconds":0,
         "collectionCopy":
            {
               "estimatedTotalBytes":694,
               "estimatedCopiedBytes":694
            },
         "directionMapping":
            {
               "Source":"cluster0: localhost:27017",
               "Destination":"cluster1: localhost:27018"
            }
      }
}
```

Thanks!

2024-04-04 14:20 UTC, mmcclimon requested changes
One more tweak; thanks!

2024-04-04 14:20 UTC, mmcclimon commented on source/includes/api/tables/progress-response.rst
> +       command succeeds and ``false`` if the command fails.
This table item is a little misleading. This table is introduced by the sentence
> If mongosync successfully gets the status of the sync process, all response fields are wrapped in a top-level `progress` object with the following fields:

The `success` key is a top-level field, not part of the `progress` object. That is: a successful response looks like this:
```javascript
{
  success: true,
  progress: {
    // All the other fields as in the table
  }
}
```

So, this description is fine, but it's a top-level field and not part of the `progress` object.

2024-04-04 20:25 UTC, sarah-olson-mongodb approved these changes
Thanks @kanchana-mongodb! LGTM

2024-04-08 13:04 UTC, mmcclimon approved these changes
LGTM % 1 small suggestion; that isn't really a technical point but a clarity one, so happy to approve without needing another review. Thanks!

2024-04-08 13:04 UTC, mmcclimon commented on source/reference/api/progress.txt
> +
(nit) Since this is in the "successful response" section, we could maybe simplify by saying here that `success` will always be true here.

2024-04-08 14:08 UTC, merged