DOCSP 39098  Recommend limiting DDL operations during a sync
mongodb/docs-cluster-to-cluster-sync pull request #311
Opened 2024-05-01 14:22 UTC by ltran-mdb2

## DESCRIPTION

Recommend limiting DDL operations during a sync

## STAGING

https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-39098/reference/mongosync/#data-definition-language--ddl--operations

## JIRA

https://jira.mongodb.org/browse/DOCSP-39098

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66324f30b67dbf804aec9d92

## SELF-REVIEW CHECKLIST

- [ ] Does each file have 3-5 taxonomy facet tags?
  See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files) 
- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## EXTERNAL REVIEW REQUIREMENTS

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-05-01 15:56 UTC, jmd-mongo approved these changes
Thanks for this update, @ltran-mdb2! This one LGTM with an optional suggestion.

Thanks!
Joe

2024-05-01 15:56 UTC, jmd-mongo commented on source/reference/mongosync.txt
> +DDL operations (operations that act on collections or databases) during
[suggestion]

Consider starting this sentence with a verb. Perhaps: "Using DDL operations ...".

2024-05-02 18:00 UTC, rohshar requested changes
I think that we need to list out examples of DDL operations or link to what they are. They aren't explained anywhere in the mongosync documentation

2024-05-06 15:56 UTC, ltran-mdb2 commented
Thanks for your feedback @rohshar ! I added examples of DDL operations and linked to more information in the manual. What do you think?

2024-05-06 16:46 UTC, ltran-mdb2 commented
Done @rohshar !

2024-05-06 19:16 UTC, rohshar approved these changes

2024-05-06 20:03 UTC, merged