(DOCSP-45558) [C2C] Mention altering load level during a migration in mongosync’s documentation.
mongodb/docs-cluster-to-cluster-sync pull request #530
Opened 2024-12-16 21:24 UTC by elyse-mdb

## DESCRIPTION
Per [this Slack thread](https://mongodb.slack.com/archives/C02SQPJHQ85/p1732128778430069), mongosync’s docs should specifically address mid-migration load level adjustments.

Suggested text:

You can adjust mongosync’s load level during a migration. To do this, terminate all mongosync processes, then restart them with the needed load level. Mongosync will resume roughly where it was before you ended the earlier processes.

2025-01-07 23:20 UTC, jwilson-mdb approved these changes
I think this came out great!! The configuration page looks to be a good home for reconfiguring, and the crosslinking seems pretty intuitive to me. Nice job.

I left a couple of small suggestions for you to review/update before requesting an ext review, but overall **LGTM**!

2025-01-07 23:20 UTC, jwilson-mdb commented on source/reference/configuration.txt
> +      To learn more, see :ref:`Initialize mongosync <c2c-initialize>`.
[nit / optional 😄  ]

Nothing wrong with "To learn more", but I think we tend to lean towards "For more information" in the server docs.

2025-01-07 23:20 UTC, jwilson-mdb commented on source/reference/mongosync.txt
> +   To disable telemetry data collection during a migration,
[question / optional]

Would it make more sense to change the order slightly here and put the configuration file link before the link to reconfigure during a migration?

Maybe an SME can chime in, but my initial thought is someone viewing this page may find the configuration file link more relevant/useful than the reconfiguration instructions.

I'm not too sure how often someone might need to reconfigure so this is a weakly held opinion.

2025-01-08 00:10 UTC, elyse-mdb commented on source/reference/mongosync.txt
> +   To disable telemetry data collection during a migration,
I was going back and forth with the ordering, so I appreciate the feedback. I agree with your reasoning here, so I moved the reconfig link below the config file link!

2025-01-08 17:26 UTC, FGasper requested changes
This looks good overall. I have a couple small-ish points; see what you think.

2025-01-08 17:26 UTC, FGasper commented on source/reference/configuration.txt
> +   You can't adjust the :setting:`cluster0`, :setting:`cluster1`, or :setting:`id` settings during a migration.
Is this list going to need further updates as further settings are added?

Something like this might be more maintainable:
> Only the following settings are adjustable during a migration. Others *MUST* remain unchanged between `mongosync` restarts.

2025-01-08 17:26 UTC, FGasper commented on source/reference/configuration.txt
> +   .. step:: (Optional) Pause the ``mongosync`` processes
What is the benefit of doing this versus just terminating the mongosync processes?

2025-01-10 18:58 UTC, elyse-mdb commented on source/reference/configuration.txt
> +   .. step:: (Optional) Pause the ``mongosync`` processes
The tip in this step (borrowed from the mongosync [Live Upgrade tutorial](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/versioning/#live-upgrade)) describes a reason why users might want to pause before terminating: 
> If you don't want to immediately resume data synchronization operations after live upgrade, consider pausing the ``mongosync`` processes. This is useful if you're coordinating operations from multiple ``mongosync`` processes.

Please let me know if you think this tip is not true or helpful! If that's the case, then I can remove this step and update the final step.

2025-01-14 14:54 UTC, merged

2025-01-14 14:56 UTC, elyse-mdb commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v1.9|[<img src="https://img.shields.io/github/pulls/detail/state/mongodb/docs-cluster-to-cluster-sync/546">](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/546)|
|✅|v1.8|[<img src="https://img.shields.io/github/pulls/detail/state/mongodb/docs-cluster-to-cluster-sync/547">](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/547)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

<!--- Backport version: 9.6.1 -->