DOCSP-22726 c2c install
mongodb/docs-cluster-to-cluster-sync pull request #9
Opened 2022-05-25 17:02 UTC by davemungo

This PR is based on the work Kenneth did in an earlier [PR](https://github.com/mongodb/docs-cluster-to-cluster-sync/pull/8/files)

[DOCSP-22726](https://jira.mongodb.org/browse/DOCSP-22726)
STAGING:

[Top level](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22726-c2c-install-v2/installation/)
[Linux](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22726-c2c-install-v2/installation/install-on-linux/)
[macOS](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-22726-c2c-install-v2/installation/install-on-macOS/)

2022-05-25 18:17 UTC, jmd-mongo reviewed
Thanks for the changes, @davemungo. I've noted two issues, but this looks solid from a copy and IA standpoint!

Thanks,
Joe

2022-05-25 18:17 UTC, jmd-mongo commented on source/installation.txt
> +:ref:`c2c-install-macos`
[broken ref]

Looks like this ref is not resolving properly:

<img width="659" alt="Screen Shot 2022-05-25 at 2 09 01 PM" src="https://user-images.githubusercontent.com/73852296/170336404-41ef7a6b-03aa-4f2b-a278-deb3c57b4e0d.png">
.

2022-05-25 18:17 UTC, jmd-mongo commented on source/includes/step-update-path.rst
> +  directory such as``/usr/local/bin`` that is already in your
[spacing]

There ought to be a space between "as" and "``/usr/local/bin``".

2022-05-25 21:23 UTC, jmd-mongo approved these changes
This one LGTM at this point. Thanks!

2022-05-26 20:35 UTC, alan-zheng-mdb requested changes

2022-05-26 23:52 UTC, davemungo reviewed
@alan-zheng-mdb thanks for the feedback, this is ready for another pass.

2022-05-27 00:50 UTC, alan-zheng-mdb approved these changes
lgtm

2022-05-27 13:06 UTC, merged